openai:
  api_key: 'api-key'
  engine: gpt-3.5-turbo-instruct

database:
  host: localhost
  port: 5432
  user: myuser
  password: mypassword
  database: mydatabase

environment:
  env: local # Possible [ local, prod ]
