version: '3.8'

services:
#  web:
#    build: .
#    command: uvicorn main:app --host 0.0.0.0
#    volumes:
#      - .:/app
#    ports:
#      - "8008:8000"
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgresql://myuser:mypassword@db/mydatabase

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
